spring:
  datasource:
    # >=6.x com.mysql.cj.jdbc.Driver
    # <=5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&useSSL=false
    hikari:
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        # 指定nacos server 地址  注意：地址前面不要加协议，直接指定IP/域名就可以了
        server-addr: 117.50.105.135:15098
        # 指定namespace 需要先在控制台进行创建(配置的是命名空间ID)
        #        namespace: 344986bd-23f3-4a76-a2e5-4c11db58fa15
        # 指定集群名称 假设在深圳机房
        cluster-name: BJ
        metadata:
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 117.50.105.135:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
  application:
    # 服务名称尽量用中划线“-” ，不要使用下划线“_”，更不要用特殊字符
    name: user-center
server:
  port: 8081
logging:
  level:
    com.alibaba.nacos: error
